// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.GetVibeRequest in examples/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

/**
 * The request to get the vibe of the server
 */
public class GetVibeRequest(
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetVibeRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetVibeRequest) return false
    if (unknownFields != other.unknownFields) return false
    return true
  }

  override fun hashCode(): Int = unknownFields.hashCode()

  override fun toString(): String = "GetVibeRequest{}"

  public fun copy(unknownFields: ByteString = this.unknownFields): GetVibeRequest = GetVibeRequest(unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetVibeRequest> = object : ProtoAdapter<GetVibeRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetVibeRequest::class, 
      "type.googleapis.com/examples.v1.GetVibeRequest", 
      PROTO_3, 
      null, 
      "examples/v1/example.proto"
    ) {
      override fun encodedSize(`value`: GetVibeRequest): Int {
        var size = value.unknownFields.size
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetVibeRequest) {
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetVibeRequest) {
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): GetVibeRequest {
        val unknownFields = reader.forEachTag(reader::readUnknownField)
        return GetVibeRequest(
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetVibeRequest): GetVibeRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
