// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.GetVibeResponse in examples/v1/example.proto
package examples.v1

import kotlin.String
import kotlinx.serialization.Serializable

/**
 * What the server is currently vibing
 */
@Serializable
public data class GetVibeResponse(
  public val vibe: String = "",
)
