// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.GetVibeRequest in examples/v1/example.proto
package examples.v1

import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlinx.serialization.Serializable

/**
 * The request to get the vibe of the server
 */
@Serializable
public class GetVibeRequest() {
  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetVibeRequest) return false
    return true
  }

  override fun hashCode(): Int = unknownFields.hashCode()
}
