// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.GetVibeRequest in examples/v1/example.proto
package examples.v1

import kotlinx.serialization.Serializable

/**
 * The request to get the vibe of the server
 */
@Serializable
public class GetVibeRequest()
