// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.VibeService in examples/v1/example.proto
package examples.v1

import io.modelcontextprotocol.kotlin.sdk.CallToolResult
import io.modelcontextprotocol.kotlin.sdk.TextContent
import io.modelcontextprotocol.kotlin.sdk.Tool
import io.modelcontextprotocol.kotlin.sdk.server.Server
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/**
 * This is a complex comment to test string processing.
 * It includes multiple lines with various characters:
 * * Special chars: "quotes", 'single-quotes', \backslashes\
 * * Symbols: @#$%^&*()_+-={}\[\]|;:<>,.?/
 * * Newlines and     multiple    spaces
 *
 * It also has empty lines and indentation:
 *   - Indented item 1
 *   - Indented item 2
 */
public class McpVibeServiceClientImpl(
  public val client: GrpcVibeServiceClient,
  public val mcpServer: Server,
) : McpVibeServiceClient {
  /**
   * This is a block comment
   * with multiple lines
   * to test block handling
   * "Hello World"
   */
  override suspend fun SetVibe(request: SetVibeRequest): SetVibeResponse {
    mcpServer.addTool(
        name = "SetVibeRequest",
        description = "This is a block comment with multiple lines to test block handling \"Hello World\"",
        inputSchema = Tool.Input(JsonObject(mapOf("null" to JsonPrimitive("null"))), required = listOf("null")),
        handler = { request ->
            CallToolResult(
                content =
                    listOf(
                        TextContent(request.toString()),
                    ),
            )
        },
    )
    return client.SetVibe(request)
  }

  /**
   * Get Vibe
   * of the server
   */
  override suspend fun GetVibe(request: GetVibeRequest): GetVibeResponse {
    mcpServer.addTool(
        name = "GetVibeRequest",
        description = "Get Vibe of the server",
        inputSchema = Tool.Input(JsonObject(mapOf("null" to JsonPrimitive("null"))), required = listOf("null")),
        handler = { request ->
            CallToolResult(
                content =
                    listOf(
                        TextContent(request.toString()),
                    ),
            )
        },
    )
    return client.GetVibe(request)
  }

  /**
   * Set vibe details
   */
  override suspend fun SetVibeDetails(request: SetVibeDetailsRequest): SetVibeResponse {
    mcpServer.addTool(
        name = "SetVibeDetailsRequest",
        description = "Set vibe details",
        inputSchema = Tool.Input(JsonObject(mapOf("null" to JsonPrimitive("null"))), required = listOf("null")),
        handler = { request ->
            CallToolResult(
                content =
                    listOf(
                        TextContent(request.toString()),
                    ),
            )
        },
    )
    return client.SetVibeDetails(request)
  }

  /**
   * Set the vibe arrays
   */
  override suspend fun SetVibeArray(request: SetVibeArrayRequest): SetVibeArrayResponse {
    mcpServer.addTool(
        name = "SetVibeArrayRequest",
        description = "Set the vibe arrays",
        inputSchema = Tool.Input(JsonObject(mapOf("null" to JsonPrimitive("null"))), required = listOf("null")),
        handler = { request ->
            CallToolResult(
                content =
                    listOf(
                        TextContent(request.toString()),
                    ),
            )
        },
    )
    return client.SetVibeArray(request)
  }

  /**
   * Set multiple vibe objects
   */
  override suspend fun SetVibeObjects(request: SetVibeObjectsRequest): SetVibeObjectsResponse {
    mcpServer.addTool(
        name = "SetVibeObjectsRequest",
        description = "Set multiple vibe objects",
        inputSchema = Tool.Input(JsonObject(mapOf("null" to JsonPrimitive("null"))), required = listOf("null")),
        handler = { request ->
            CallToolResult(
                content =
                    listOf(
                        TextContent(request.toString()),
                    ),
            )
        },
    )
    return client.SetVibeObjects(request)
  }
}
