// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.VibeService in examples/v1/example.proto
package examples.v1

/**
 * This is a complex comment to test string processing.
 * It includes multiple lines with various characters:
 * * Special chars: "quotes", 'single-quotes', \backslashes\
 * * Symbols: @#$%^&*()_+-={}\[\]|;:<>,.?/
 * * Newlines and     multiple    spaces
 *
 * It also has empty lines and indentation:
 *   - Indented item 1
 *   - Indented item 2
 */
public interface McpVibeServiceClient {
  /**
   * This is a block comment
   * with multiple lines
   * to test block handling
   * "Hello World"
   */
  public suspend fun SetVibe(request: SetVibeRequest): SetVibeResponse

  /**
   * Get Vibe
   * of the server
   */
  public suspend fun GetVibe(request: GetVibeRequest): GetVibeResponse

  /**
   * Set vibe details
   */
  public suspend fun SetVibeDetails(request: SetVibeDetailsRequest): SetVibeResponse

  /**
   * Set the vibe arrays
   */
  public suspend fun SetVibeArray(request: SetVibeArrayRequest): SetVibeArrayResponse

  /**
   * Set multiple vibe objects
   */
  public suspend fun SetVibeObjects(request: SetVibeObjectsRequest): SetVibeObjectsResponse
}
