// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeObjectsResponse in examples/v1/example.proto
package examples.v1

import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.collections.List
import kotlinx.serialization.Serializable

/**
 * The response to set multiple vibe objects on the server
 */
@Serializable
public data class SetVibeObjectsResponse(
  /**
   * The details of the vibe
   */
  public val vibeObject: List<SomeVibeObject> = emptyList(),
) {
  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SetVibeObjectsResponse) return false
    if (vibeObject != other.vibeObject) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode()
    if (result == 0) {
      result = result * 37 + vibeObject.hashCode()
    }
    return result
  }
}
