// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeObjectsResponse in examples/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import okio.ByteString

/**
 * The response to set multiple vibe objects on the server
 */
public class SetVibeObjectsResponse(
  vibe_object: List<SomeVibeObject> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SetVibeObjectsResponse, Nothing>(ADAPTER, unknownFields) {
  /**
   * The details of the vibe
   */
  @field:WireField(
    tag = 1,
    adapter = "examples.v1.SomeVibeObject#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "vibeObject",
    schemaIndex = 0,
  )
  public val vibe_object: List<SomeVibeObject> = immutableCopyOf("vibe_object", vibe_object)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SetVibeObjectsResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (vibe_object != other.vibe_object) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + vibe_object.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (vibe_object.isNotEmpty()) result += """vibe_object=$vibe_object"""
    return result.joinToString(prefix = "SetVibeObjectsResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(vibe_object: List<SomeVibeObject> = this.vibe_object, unknownFields: ByteString = this.unknownFields): SetVibeObjectsResponse = SetVibeObjectsResponse(vibe_object, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SetVibeObjectsResponse> =
        object : ProtoAdapter<SetVibeObjectsResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      SetVibeObjectsResponse::class, 
      "type.googleapis.com/examples.v1.SetVibeObjectsResponse", 
      PROTO_3, 
      null, 
      "examples/v1/example.proto"
    ) {
      override fun encodedSize(`value`: SetVibeObjectsResponse): Int {
        var size = value.unknownFields.size
        size += SomeVibeObject.ADAPTER.asRepeated().encodedSizeWithTag(1, value.vibe_object)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SetVibeObjectsResponse) {
        SomeVibeObject.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.vibe_object)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SetVibeObjectsResponse) {
        writer.writeBytes(value.unknownFields)
        SomeVibeObject.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.vibe_object)
      }

      override fun decode(reader: ProtoReader): SetVibeObjectsResponse {
        val vibe_object = mutableListOf<SomeVibeObject>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> vibe_object.add(SomeVibeObject.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return SetVibeObjectsResponse(
          vibe_object = vibe_object,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SetVibeObjectsResponse): SetVibeObjectsResponse = value.copy(
        vibe_object = value.vibe_object.redactElements(SomeVibeObject.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
