// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeRequest in examples/v1/example.proto
package examples.v1

import kotlin.String
import kotlinx.serialization.Serializable

/**
 * The request to set the vibe of the server
 */
@Serializable
public data class SetVibeRequest(
  /**
   * The vibe of the server to be set
   */
  public val vibe: String = "",
)
