// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeArrayResponse in examples/v1/example.proto
package examples.v1

import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlinx.serialization.Serializable

/**
 * The vibe array response
 */
@Serializable
public data class SetVibeArrayResponse(
  /**
   * The details of the vibe array
   */
  public val vibeArray: VibeArray? = null,
) {
  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SetVibeArrayResponse) return false
    if (vibeArray != other.vibeArray) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode()
    if (result == 0) {
      result = result * 37 + (vibeArray?.hashCode() ?: 0)
    }
    return result
  }
}
