// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeResponse in examples/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

/**
 * the new vibe of the server
 */
public class SetVibeResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "previousVibe",
    schemaIndex = 0,
  )
  public val previous_vibe: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val vibe: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SetVibeResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SetVibeResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (previous_vibe != other.previous_vibe) return false
    if (vibe != other.vibe) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + previous_vibe.hashCode()
      result = result * 37 + vibe.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """previous_vibe=${sanitize(previous_vibe)}"""
    result += """vibe=${sanitize(vibe)}"""
    return result.joinToString(prefix = "SetVibeResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    previous_vibe: String = this.previous_vibe,
    vibe: String = this.vibe,
    unknownFields: ByteString = this.unknownFields,
  ): SetVibeResponse = SetVibeResponse(previous_vibe, vibe, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SetVibeResponse> = object : ProtoAdapter<SetVibeResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      SetVibeResponse::class, 
      "type.googleapis.com/examples.v1.SetVibeResponse", 
      PROTO_3, 
      null, 
      "examples/v1/example.proto"
    ) {
      override fun encodedSize(`value`: SetVibeResponse): Int {
        var size = value.unknownFields.size
        if (value.previous_vibe != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.previous_vibe)
        }
        if (value.vibe != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.vibe)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SetVibeResponse) {
        if (value.previous_vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.previous_vibe)
        }
        if (value.vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.vibe)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SetVibeResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.vibe)
        }
        if (value.previous_vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.previous_vibe)
        }
      }

      override fun decode(reader: ProtoReader): SetVibeResponse {
        var previous_vibe: String = ""
        var vibe: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> previous_vibe = ProtoAdapter.STRING.decode(reader)
            2 -> vibe = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SetVibeResponse(
          previous_vibe = previous_vibe,
          vibe = vibe,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SetVibeResponse): SetVibeResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
