// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeResponse in examples/v1/example.proto
package examples.v1

import kotlin.String
import kotlinx.serialization.Serializable

/**
 * the new vibe of the server
 */
@Serializable
public data class SetVibeResponse(
  public val previousVibe: String = "",
  public val vibe: String = "",
)
