// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeArrayResponse in examples/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

/**
 * The vibe array response
 */
public class SetVibeArrayResponse(
  /**
   * The details of the vibe array
   */
  @field:WireField(
    tag = 1,
    adapter = "examples.v1.VibeArray#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "vibeArray",
    schemaIndex = 0,
  )
  public val vibe_array: VibeArray? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SetVibeArrayResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SetVibeArrayResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (vibe_array != other.vibe_array) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (vibe_array?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (vibe_array != null) result += """vibe_array=$vibe_array"""
    return result.joinToString(prefix = "SetVibeArrayResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(vibe_array: VibeArray? = this.vibe_array, unknownFields: ByteString = this.unknownFields): SetVibeArrayResponse = SetVibeArrayResponse(vibe_array, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SetVibeArrayResponse> =
        object : ProtoAdapter<SetVibeArrayResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      SetVibeArrayResponse::class, 
      "type.googleapis.com/examples.v1.SetVibeArrayResponse", 
      PROTO_3, 
      null, 
      "examples/v1/example.proto"
    ) {
      override fun encodedSize(`value`: SetVibeArrayResponse): Int {
        var size = value.unknownFields.size
        if (value.vibe_array != null) {
          size += VibeArray.ADAPTER.encodedSizeWithTag(1, value.vibe_array)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SetVibeArrayResponse) {
        if (value.vibe_array != null) {
          VibeArray.ADAPTER.encodeWithTag(writer, 1, value.vibe_array)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SetVibeArrayResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.vibe_array != null) {
          VibeArray.ADAPTER.encodeWithTag(writer, 1, value.vibe_array)
        }
      }

      override fun decode(reader: ProtoReader): SetVibeArrayResponse {
        var vibe_array: VibeArray? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> vibe_array = VibeArray.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SetVibeArrayResponse(
          vibe_array = vibe_array,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SetVibeArrayResponse): SetVibeArrayResponse = value.copy(
        vibe_array = value.vibe_array?.let(VibeArray.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
