// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeResponse in examples/v1/example.proto
package examples.v1

import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable

/**
 * the new vibe of the server
 */
@Serializable
public data class SetVibeResponse(
  public val previousVibe: String = "",
  public val vibe: String = "",
) {
  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SetVibeResponse) return false
    if (previousVibe != other.previousVibe) return false
    if (vibe != other.vibe) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode()
    if (result == 0) {
      result = result * 37 + previousVibe.hashCode()
      result = result * 37 + vibe.hashCode()
    }
    return result
  }
}
