// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeRequest in examples/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

/**
 * The request to set the vibe of the server
 */
public class SetVibeRequest(
  /**
   * The vibe of the server to be set
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val vibe: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SetVibeRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SetVibeRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (vibe != other.vibe) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + vibe.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """vibe=${sanitize(vibe)}"""
    return result.joinToString(prefix = "SetVibeRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(vibe: String = this.vibe, unknownFields: ByteString = this.unknownFields): SetVibeRequest = SetVibeRequest(vibe, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SetVibeRequest> = object : ProtoAdapter<SetVibeRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      SetVibeRequest::class, 
      "type.googleapis.com/examples.v1.SetVibeRequest", 
      PROTO_3, 
      null, 
      "examples/v1/example.proto"
    ) {
      override fun encodedSize(`value`: SetVibeRequest): Int {
        var size = value.unknownFields.size
        if (value.vibe != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.vibe)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SetVibeRequest) {
        if (value.vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.vibe)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SetVibeRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.vibe)
        }
      }

      override fun decode(reader: ProtoReader): SetVibeRequest {
        var vibe: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> vibe = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SetVibeRequest(
          vibe = vibe,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SetVibeRequest): SetVibeRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
