// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeDetailsRequest in examples/v1/example.proto
package examples.v1

import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable

/**
 * The detailed vibe of the server
 */
@Serializable
public data class SetVibeDetailsRequest(
  /**
   * The vibe of the string to be set
   */
  public val vibe: String = "",
  /**
   * The details of the vibe
   */
  public val vibeScalar: VibeScalar? = null,
) {
  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SetVibeDetailsRequest) return false
    if (vibe != other.vibe) return false
    if (vibeScalar != other.vibeScalar) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode()
    if (result == 0) {
      result = result * 37 + vibe.hashCode()
      result = result * 37 + (vibeScalar?.hashCode() ?: 0)
    }
    return result
  }
}
