// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.VibeArray in examples/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import okio.ByteString

/**
 * The vibe array message
 */
public class VibeArray(
  vibe_doubles: List<Double> = emptyList(),
  vibe_floats: List<Float> = emptyList(),
  vibe_int32s: List<Int> = emptyList(),
  vibe_int64s: List<Long> = emptyList(),
  vibe_uint32s: List<Int> = emptyList(),
  vibe_uint64s: List<Long> = emptyList(),
  vibe_sint32s: List<Int> = emptyList(),
  vibe_sint64s: List<Long> = emptyList(),
  vibe_fixed32s: List<Int> = emptyList(),
  vibe_fixed64s: List<Long> = emptyList(),
  vibe_sfixed32s: List<Int> = emptyList(),
  vibe_sfixed64s: List<Long> = emptyList(),
  vibe_bools: List<Boolean> = emptyList(),
  vibe_byteses: List<ByteString> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<VibeArray, Nothing>(ADAPTER, unknownFields) {
  /**
   * The details of the vibe double array
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    label = WireField.Label.PACKED,
    jsonName = "vibeDoubles",
    schemaIndex = 0,
  )
  public val vibe_doubles: List<Double> = immutableCopyOf("vibe_doubles", vibe_doubles)

  /**
   * the details of the vibe float array
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.PACKED,
    jsonName = "vibeFloats",
    schemaIndex = 1,
  )
  public val vibe_floats: List<Float> = immutableCopyOf("vibe_floats", vibe_floats)

  /**
   * The details of the vibe int32 array
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.PACKED,
    jsonName = "vibeInt32s",
    schemaIndex = 2,
  )
  public val vibe_int32s: List<Int> = immutableCopyOf("vibe_int32s", vibe_int32s)

  /**
   * The details of the vibe int64 array
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.PACKED,
    jsonName = "vibeInt64s",
    schemaIndex = 3,
  )
  public val vibe_int64s: List<Long> = immutableCopyOf("vibe_int64s", vibe_int64s)

  /**
   * The details of the vibe uint32 array
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.PACKED,
    jsonName = "vibeUint32s",
    schemaIndex = 4,
  )
  public val vibe_uint32s: List<Int> = immutableCopyOf("vibe_uint32s", vibe_uint32s)

  /**
   * The details of the vibe uint64 array
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.PACKED,
    jsonName = "vibeUint64s",
    schemaIndex = 5,
  )
  public val vibe_uint64s: List<Long> = immutableCopyOf("vibe_uint64s", vibe_uint64s)

  /**
   * The details of the vibe sint32 array
   */
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#SINT32",
    label = WireField.Label.PACKED,
    jsonName = "vibeSint32s",
    schemaIndex = 6,
  )
  public val vibe_sint32s: List<Int> = immutableCopyOf("vibe_sint32s", vibe_sint32s)

  /**
   * The details of the vibe sint64 array
   */
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#SINT64",
    label = WireField.Label.PACKED,
    jsonName = "vibeSint64s",
    schemaIndex = 7,
  )
  public val vibe_sint64s: List<Long> = immutableCopyOf("vibe_sint64s", vibe_sint64s)

  /**
   * The details of the vibe fixed32 array
   */
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.PACKED,
    jsonName = "vibeFixed32s",
    schemaIndex = 8,
  )
  public val vibe_fixed32s: List<Int> = immutableCopyOf("vibe_fixed32s", vibe_fixed32s)

  /**
   * The details of the vibe fixed64 array
   */
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED64",
    label = WireField.Label.PACKED,
    jsonName = "vibeFixed64s",
    schemaIndex = 9,
  )
  public val vibe_fixed64s: List<Long> = immutableCopyOf("vibe_fixed64s", vibe_fixed64s)

  /**
   * The details of the vibe sfixed32 array
   */
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#SFIXED32",
    label = WireField.Label.PACKED,
    jsonName = "vibeSfixed32s",
    schemaIndex = 10,
  )
  public val vibe_sfixed32s: List<Int> = immutableCopyOf("vibe_sfixed32s", vibe_sfixed32s)

  /**
   * The details of the vibe sfixed64 array
   */
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#SFIXED64",
    label = WireField.Label.PACKED,
    jsonName = "vibeSfixed64s",
    schemaIndex = 11,
  )
  public val vibe_sfixed64s: List<Long> = immutableCopyOf("vibe_sfixed64s", vibe_sfixed64s)

  /**
   * The details of the vibe bool array
   */
  @field:WireField(
    tag = 14,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.REPEATED,
    jsonName = "vibeBools",
    schemaIndex = 12,
  )
  public val vibe_bools: List<Boolean> = immutableCopyOf("vibe_bools", vibe_bools)

  /**
   * the details of the vibe bytes array
   */
  @field:WireField(
    tag = 15,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.REPEATED,
    jsonName = "vibeByteses",
    schemaIndex = 13,
  )
  public val vibe_byteses: List<ByteString> = immutableCopyOf("vibe_byteses", vibe_byteses)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is VibeArray) return false
    if (unknownFields != other.unknownFields) return false
    if (vibe_doubles != other.vibe_doubles) return false
    if (vibe_floats != other.vibe_floats) return false
    if (vibe_int32s != other.vibe_int32s) return false
    if (vibe_int64s != other.vibe_int64s) return false
    if (vibe_uint32s != other.vibe_uint32s) return false
    if (vibe_uint64s != other.vibe_uint64s) return false
    if (vibe_sint32s != other.vibe_sint32s) return false
    if (vibe_sint64s != other.vibe_sint64s) return false
    if (vibe_fixed32s != other.vibe_fixed32s) return false
    if (vibe_fixed64s != other.vibe_fixed64s) return false
    if (vibe_sfixed32s != other.vibe_sfixed32s) return false
    if (vibe_sfixed64s != other.vibe_sfixed64s) return false
    if (vibe_bools != other.vibe_bools) return false
    if (vibe_byteses != other.vibe_byteses) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + vibe_doubles.hashCode()
      result = result * 37 + vibe_floats.hashCode()
      result = result * 37 + vibe_int32s.hashCode()
      result = result * 37 + vibe_int64s.hashCode()
      result = result * 37 + vibe_uint32s.hashCode()
      result = result * 37 + vibe_uint64s.hashCode()
      result = result * 37 + vibe_sint32s.hashCode()
      result = result * 37 + vibe_sint64s.hashCode()
      result = result * 37 + vibe_fixed32s.hashCode()
      result = result * 37 + vibe_fixed64s.hashCode()
      result = result * 37 + vibe_sfixed32s.hashCode()
      result = result * 37 + vibe_sfixed64s.hashCode()
      result = result * 37 + vibe_bools.hashCode()
      result = result * 37 + vibe_byteses.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (vibe_doubles.isNotEmpty()) result += """vibe_doubles=$vibe_doubles"""
    if (vibe_floats.isNotEmpty()) result += """vibe_floats=$vibe_floats"""
    if (vibe_int32s.isNotEmpty()) result += """vibe_int32s=$vibe_int32s"""
    if (vibe_int64s.isNotEmpty()) result += """vibe_int64s=$vibe_int64s"""
    if (vibe_uint32s.isNotEmpty()) result += """vibe_uint32s=$vibe_uint32s"""
    if (vibe_uint64s.isNotEmpty()) result += """vibe_uint64s=$vibe_uint64s"""
    if (vibe_sint32s.isNotEmpty()) result += """vibe_sint32s=$vibe_sint32s"""
    if (vibe_sint64s.isNotEmpty()) result += """vibe_sint64s=$vibe_sint64s"""
    if (vibe_fixed32s.isNotEmpty()) result += """vibe_fixed32s=$vibe_fixed32s"""
    if (vibe_fixed64s.isNotEmpty()) result += """vibe_fixed64s=$vibe_fixed64s"""
    if (vibe_sfixed32s.isNotEmpty()) result += """vibe_sfixed32s=$vibe_sfixed32s"""
    if (vibe_sfixed64s.isNotEmpty()) result += """vibe_sfixed64s=$vibe_sfixed64s"""
    if (vibe_bools.isNotEmpty()) result += """vibe_bools=$vibe_bools"""
    if (vibe_byteses.isNotEmpty()) result += """vibe_byteses=$vibe_byteses"""
    return result.joinToString(prefix = "VibeArray{", separator = ", ", postfix = "}")
  }

  public fun copy(
    vibe_doubles: List<Double> = this.vibe_doubles,
    vibe_floats: List<Float> = this.vibe_floats,
    vibe_int32s: List<Int> = this.vibe_int32s,
    vibe_int64s: List<Long> = this.vibe_int64s,
    vibe_uint32s: List<Int> = this.vibe_uint32s,
    vibe_uint64s: List<Long> = this.vibe_uint64s,
    vibe_sint32s: List<Int> = this.vibe_sint32s,
    vibe_sint64s: List<Long> = this.vibe_sint64s,
    vibe_fixed32s: List<Int> = this.vibe_fixed32s,
    vibe_fixed64s: List<Long> = this.vibe_fixed64s,
    vibe_sfixed32s: List<Int> = this.vibe_sfixed32s,
    vibe_sfixed64s: List<Long> = this.vibe_sfixed64s,
    vibe_bools: List<Boolean> = this.vibe_bools,
    vibe_byteses: List<ByteString> = this.vibe_byteses,
    unknownFields: ByteString = this.unknownFields,
  ): VibeArray = VibeArray(vibe_doubles, vibe_floats, vibe_int32s, vibe_int64s, vibe_uint32s, vibe_uint64s, vibe_sint32s, vibe_sint64s, vibe_fixed32s, vibe_fixed64s, vibe_sfixed32s, vibe_sfixed64s, vibe_bools, vibe_byteses, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<VibeArray> = object : ProtoAdapter<VibeArray>(
      FieldEncoding.LENGTH_DELIMITED, 
      VibeArray::class, 
      "type.googleapis.com/examples.v1.VibeArray", 
      PROTO_3, 
      null, 
      "examples/v1/example.proto"
    ) {
      override fun encodedSize(`value`: VibeArray): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.DOUBLE.asPacked().encodedSizeWithTag(2, value.vibe_doubles)
        size += ProtoAdapter.FLOAT.asPacked().encodedSizeWithTag(3, value.vibe_floats)
        size += ProtoAdapter.INT32.asPacked().encodedSizeWithTag(4, value.vibe_int32s)
        size += ProtoAdapter.INT64.asPacked().encodedSizeWithTag(5, value.vibe_int64s)
        size += ProtoAdapter.UINT32.asPacked().encodedSizeWithTag(6, value.vibe_uint32s)
        size += ProtoAdapter.UINT64.asPacked().encodedSizeWithTag(7, value.vibe_uint64s)
        size += ProtoAdapter.SINT32.asPacked().encodedSizeWithTag(8, value.vibe_sint32s)
        size += ProtoAdapter.SINT64.asPacked().encodedSizeWithTag(9, value.vibe_sint64s)
        size += ProtoAdapter.FIXED32.asPacked().encodedSizeWithTag(10, value.vibe_fixed32s)
        size += ProtoAdapter.FIXED64.asPacked().encodedSizeWithTag(11, value.vibe_fixed64s)
        size += ProtoAdapter.SFIXED32.asPacked().encodedSizeWithTag(12, value.vibe_sfixed32s)
        size += ProtoAdapter.SFIXED64.asPacked().encodedSizeWithTag(13, value.vibe_sfixed64s)
        size += ProtoAdapter.BOOL.asRepeated().encodedSizeWithTag(14, value.vibe_bools)
        size += ProtoAdapter.BYTES.asRepeated().encodedSizeWithTag(15, value.vibe_byteses)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: VibeArray) {
        ProtoAdapter.DOUBLE.asPacked().encodeWithTag(writer, 2, value.vibe_doubles)
        ProtoAdapter.FLOAT.asPacked().encodeWithTag(writer, 3, value.vibe_floats)
        ProtoAdapter.INT32.asPacked().encodeWithTag(writer, 4, value.vibe_int32s)
        ProtoAdapter.INT64.asPacked().encodeWithTag(writer, 5, value.vibe_int64s)
        ProtoAdapter.UINT32.asPacked().encodeWithTag(writer, 6, value.vibe_uint32s)
        ProtoAdapter.UINT64.asPacked().encodeWithTag(writer, 7, value.vibe_uint64s)
        ProtoAdapter.SINT32.asPacked().encodeWithTag(writer, 8, value.vibe_sint32s)
        ProtoAdapter.SINT64.asPacked().encodeWithTag(writer, 9, value.vibe_sint64s)
        ProtoAdapter.FIXED32.asPacked().encodeWithTag(writer, 10, value.vibe_fixed32s)
        ProtoAdapter.FIXED64.asPacked().encodeWithTag(writer, 11, value.vibe_fixed64s)
        ProtoAdapter.SFIXED32.asPacked().encodeWithTag(writer, 12, value.vibe_sfixed32s)
        ProtoAdapter.SFIXED64.asPacked().encodeWithTag(writer, 13, value.vibe_sfixed64s)
        ProtoAdapter.BOOL.asRepeated().encodeWithTag(writer, 14, value.vibe_bools)
        ProtoAdapter.BYTES.asRepeated().encodeWithTag(writer, 15, value.vibe_byteses)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: VibeArray) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.BYTES.asRepeated().encodeWithTag(writer, 15, value.vibe_byteses)
        ProtoAdapter.BOOL.asRepeated().encodeWithTag(writer, 14, value.vibe_bools)
        ProtoAdapter.SFIXED64.asPacked().encodeWithTag(writer, 13, value.vibe_sfixed64s)
        ProtoAdapter.SFIXED32.asPacked().encodeWithTag(writer, 12, value.vibe_sfixed32s)
        ProtoAdapter.FIXED64.asPacked().encodeWithTag(writer, 11, value.vibe_fixed64s)
        ProtoAdapter.FIXED32.asPacked().encodeWithTag(writer, 10, value.vibe_fixed32s)
        ProtoAdapter.SINT64.asPacked().encodeWithTag(writer, 9, value.vibe_sint64s)
        ProtoAdapter.SINT32.asPacked().encodeWithTag(writer, 8, value.vibe_sint32s)
        ProtoAdapter.UINT64.asPacked().encodeWithTag(writer, 7, value.vibe_uint64s)
        ProtoAdapter.UINT32.asPacked().encodeWithTag(writer, 6, value.vibe_uint32s)
        ProtoAdapter.INT64.asPacked().encodeWithTag(writer, 5, value.vibe_int64s)
        ProtoAdapter.INT32.asPacked().encodeWithTag(writer, 4, value.vibe_int32s)
        ProtoAdapter.FLOAT.asPacked().encodeWithTag(writer, 3, value.vibe_floats)
        ProtoAdapter.DOUBLE.asPacked().encodeWithTag(writer, 2, value.vibe_doubles)
      }

      override fun decode(reader: ProtoReader): VibeArray {
        var vibe_doubles: MutableList<Double>? = null
        var vibe_floats: MutableList<Float>? = null
        var vibe_int32s: MutableList<Int>? = null
        var vibe_int64s: MutableList<Long>? = null
        var vibe_uint32s: MutableList<Int>? = null
        var vibe_uint64s: MutableList<Long>? = null
        var vibe_sint32s: MutableList<Int>? = null
        var vibe_sint64s: MutableList<Long>? = null
        var vibe_fixed32s: MutableList<Int>? = null
        var vibe_fixed64s: MutableList<Long>? = null
        var vibe_sfixed32s: MutableList<Int>? = null
        var vibe_sfixed64s: MutableList<Long>? = null
        val vibe_bools = mutableListOf<Boolean>()
        val vibe_byteses = mutableListOf<ByteString>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            2 -> {
              if (vibe_doubles == null) {
                val minimumByteSize = 8
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_doubles = ArrayList(initialCapacity)
              }
              vibe_doubles!!.add(ProtoAdapter.DOUBLE.decode(reader))
            }
            3 -> {
              if (vibe_floats == null) {
                val minimumByteSize = 4
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_floats = ArrayList(initialCapacity)
              }
              vibe_floats!!.add(ProtoAdapter.FLOAT.decode(reader))
            }
            4 -> {
              if (vibe_int32s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_int32s = ArrayList(initialCapacity)
              }
              vibe_int32s!!.add(ProtoAdapter.INT32.decode(reader))
            }
            5 -> {
              if (vibe_int64s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_int64s = ArrayList(initialCapacity)
              }
              vibe_int64s!!.add(ProtoAdapter.INT64.decode(reader))
            }
            6 -> {
              if (vibe_uint32s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_uint32s = ArrayList(initialCapacity)
              }
              vibe_uint32s!!.add(ProtoAdapter.UINT32.decode(reader))
            }
            7 -> {
              if (vibe_uint64s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_uint64s = ArrayList(initialCapacity)
              }
              vibe_uint64s!!.add(ProtoAdapter.UINT64.decode(reader))
            }
            8 -> {
              if (vibe_sint32s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_sint32s = ArrayList(initialCapacity)
              }
              vibe_sint32s!!.add(ProtoAdapter.SINT32.decode(reader))
            }
            9 -> {
              if (vibe_sint64s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_sint64s = ArrayList(initialCapacity)
              }
              vibe_sint64s!!.add(ProtoAdapter.SINT64.decode(reader))
            }
            10 -> {
              if (vibe_fixed32s == null) {
                val minimumByteSize = 4
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_fixed32s = ArrayList(initialCapacity)
              }
              vibe_fixed32s!!.add(ProtoAdapter.FIXED32.decode(reader))
            }
            11 -> {
              if (vibe_fixed64s == null) {
                val minimumByteSize = 8
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_fixed64s = ArrayList(initialCapacity)
              }
              vibe_fixed64s!!.add(ProtoAdapter.FIXED64.decode(reader))
            }
            12 -> {
              if (vibe_sfixed32s == null) {
                val minimumByteSize = 4
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_sfixed32s = ArrayList(initialCapacity)
              }
              vibe_sfixed32s!!.add(ProtoAdapter.SFIXED32.decode(reader))
            }
            13 -> {
              if (vibe_sfixed64s == null) {
                val minimumByteSize = 8
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_sfixed64s = ArrayList(initialCapacity)
              }
              vibe_sfixed64s!!.add(ProtoAdapter.SFIXED64.decode(reader))
            }
            14 -> vibe_bools.add(ProtoAdapter.BOOL.decode(reader))
            15 -> vibe_byteses.add(ProtoAdapter.BYTES.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return VibeArray(
          vibe_doubles = vibe_doubles ?: listOf(),
          vibe_floats = vibe_floats ?: listOf(),
          vibe_int32s = vibe_int32s ?: listOf(),
          vibe_int64s = vibe_int64s ?: listOf(),
          vibe_uint32s = vibe_uint32s ?: listOf(),
          vibe_uint64s = vibe_uint64s ?: listOf(),
          vibe_sint32s = vibe_sint32s ?: listOf(),
          vibe_sint64s = vibe_sint64s ?: listOf(),
          vibe_fixed32s = vibe_fixed32s ?: listOf(),
          vibe_fixed64s = vibe_fixed64s ?: listOf(),
          vibe_sfixed32s = vibe_sfixed32s ?: listOf(),
          vibe_sfixed64s = vibe_sfixed64s ?: listOf(),
          vibe_bools = vibe_bools,
          vibe_byteses = vibe_byteses,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: VibeArray): VibeArray = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
