// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.VibeService in examples/v1/example.proto
package examples.v1

import com.squareup.wire.Service
import com.squareup.wire.WireRpc

/**
 * This is a complex comment to test string processing.
 * It includes multiple lines with various characters:
 * * Special chars: "quotes", 'single-quotes', \backslashes\
 * * Symbols: @#$%^&*()_+-={}\[\]|;:<>,.?/
 * * Newlines and     multiple    spaces
 *
 * It also has empty lines and indentation:
 *   - Indented item 1
 *   - Indented item 2
 */
public interface VibeServiceServer : Service {
  /**
   * This is a block comment
   * with multiple lines
   * to test block handling
   * "Hello World"
   */
  @WireRpc(
    path = "/examples.v1.VibeService/SetVibe",
    requestAdapter = "examples.v1.SetVibeRequest#ADAPTER",
    responseAdapter = "examples.v1.SetVibeResponse#ADAPTER",
    sourceFile = "examples/v1/example.proto",
  )
  public suspend fun SetVibe(request: SetVibeRequest): SetVibeResponse

  /**
   * Get Vibe
   * of the server
   */
  @WireRpc(
    path = "/examples.v1.VibeService/GetVibe",
    requestAdapter = "examples.v1.GetVibeRequest#ADAPTER",
    responseAdapter = "examples.v1.GetVibeResponse#ADAPTER",
    sourceFile = "examples/v1/example.proto",
  )
  public suspend fun GetVibe(request: GetVibeRequest): GetVibeResponse

  /**
   * Set vibe details
   */
  @WireRpc(
    path = "/examples.v1.VibeService/SetVibeDetails",
    requestAdapter = "examples.v1.SetVibeDetailsRequest#ADAPTER",
    responseAdapter = "examples.v1.SetVibeResponse#ADAPTER",
    sourceFile = "examples/v1/example.proto",
  )
  public suspend fun SetVibeDetails(request: SetVibeDetailsRequest): SetVibeResponse

  /**
   * Set the vibe arrays
   */
  @WireRpc(
    path = "/examples.v1.VibeService/SetVibeArray",
    requestAdapter = "examples.v1.SetVibeArrayRequest#ADAPTER",
    responseAdapter = "examples.v1.SetVibeArrayResponse#ADAPTER",
    sourceFile = "examples/v1/example.proto",
  )
  public suspend fun SetVibeArray(request: SetVibeArrayRequest): SetVibeArrayResponse

  /**
   * Set multiple vibe objects
   */
  @WireRpc(
    path = "/examples.v1.VibeService/SetVibeObjects",
    requestAdapter = "examples.v1.SetVibeObjectsRequest#ADAPTER",
    responseAdapter = "examples.v1.SetVibeObjectsResponse#ADAPTER",
    sourceFile = "examples/v1/example.proto",
  )
  public suspend fun SetVibeObjects(request: SetVibeObjectsRequest): SetVibeObjectsResponse
}
