version: '3.8'

services:
  protoc-gen-kotlin-mcp-server:
    image: ${REGISTRY}/${PROJECT_NAME}:${JAR_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_VERSION: ${JAR_VERSION}
    ports:
      - "9090:2345" # Map the container port to the host
    working_dir: /app
