// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.GetVibeRequest in examples/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.`internal`.JvmField
import kotlinx.serialization.Serializable
import kotlin.Int
import kotlin.Long

/**
 * The request to get the vibe of the server
 */
@Serializable
class GetVibeRequest() {
    fun copy(): GetVibeRequest = GetVibeRequest()

    companion object {
        @JvmField
        val ADAPTER: ProtoAdapter<GetVibeRequest> =
            object : ProtoAdapter<GetVibeRequest>(
                FieldEncoding.LENGTH_DELIMITED,
                GetVibeRequest::class,
                "type.googleapis.com/examples.v1.GetVibeRequest",
                PROTO_3,
                null,
                "examples/v1/example.proto",
            ) {
                override fun encodedSize(`value`: GetVibeRequest): Int {
                    var size = 0
                    return size
                }

                override fun encode(
                    writer: ProtoWriter,
                    `value`: GetVibeRequest,
                ) {
                }

                override fun encode(
                    writer: ReverseProtoWriter,
                    `value`: GetVibeRequest,
                ) {
                }

                override fun decode(reader: ProtoReader): GetVibeRequest {
                    val unknownFields = reader.forEachTag(reader::readUnknownField)
                    return GetVibeRequest()
                }

                override fun redact(`value`: GetVibeRequest): GetVibeRequest = value
            }

        private const val serialVersionUID: Long = 0L
    }
}
