// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.VibeService in example/v1/example.proto
package examples.v1

import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import okio.ByteString.Companion.toByteString

/**
 * This is a complex comment to test string processing.
 * It includes multiple lines with various characters:
 * * Special chars: "quotes", 'single-quotes', \backslashes\
 * * Symbols: @#$%^&*()_+-={}\[\]|;:<>,.?/
 * * Newlines and     multiple    spaces
 *
 * It also has empty lines and indentation:
 *   - Indented item 1
 *   - Indented item 2
 */
class GrpcVibeServiceClient(
  private val client: GrpcClient,
) : VibeServiceClient {
  /**
   * This is a block comment
   * with multiple lines
   * to test block handling
   * "Hello World"
   */
  override suspend fun SetVibe(request: SetVibeRequest): SetVibeResponse {
    val call = client.newCall(GrpcMethod(
        path = "/examples.v1.VibeService/SetVibe",
        requestAdapter = SetVibeRequest.ADAPTER,
        responseAdapter = SetVibeResponse.ADAPTER
    ))
    return call.execute(request)
  }

  /**
   * Get Vibe
   * of the server
   */
  override suspend fun GetVibe(request: GetVibeRequest): GetVibeResponse {
    val call = client.newCall(GrpcMethod(
        path = "/examples.v1.VibeService/GetVibe",
        requestAdapter = GetVibeRequest.ADAPTER,
        responseAdapter = GetVibeResponse.ADAPTER
    ))
    return call.execute(request)
  }

  /**
   * Set vibe details
   */
  override suspend fun SetVibeDetails(request: SetVibeDetailsRequest): SetVibeResponse {
    val call = client.newCall(GrpcMethod(
        path = "/examples.v1.VibeService/SetVibeDetails",
        requestAdapter = SetVibeDetailsRequest.ADAPTER,
        responseAdapter = SetVibeResponse.ADAPTER
    ))
    return call.execute(request)
  }

  /**
   * Set the vibe arrays
   */
  override suspend fun SetVibeArray(request: SetVibeArrayRequest): SetVibeArrayResponse {
    val call = client.newCall(GrpcMethod(
        path = "/examples.v1.VibeService/SetVibeArray",
        requestAdapter = SetVibeArrayRequest.ADAPTER,
        responseAdapter = SetVibeArrayResponse.ADAPTER
    ))
    return call.execute(request)
  }

  /**
   * Set multiple vibe objects
   */
  override suspend fun SetVibeObjects(request: SetVibeObjectsRequest): SetVibeObjectsResponse {
    val call = client.newCall(GrpcMethod(
        path = "/examples.v1.VibeService/SetVibeObjects",
        requestAdapter = SetVibeObjectsRequest.ADAPTER,
        responseAdapter = SetVibeObjectsResponse.ADAPTER
    ))
    return call.execute(request)
  }
}
