// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.VibeService in example/v1/example.proto
package examples.v1

import io.modelcontextprotocol.kotlin.sdk.CallToolResult
import io.modelcontextprotocol.kotlin.sdk.ReadResourceResult
import io.modelcontextprotocol.kotlin.sdk.TextContent
import io.modelcontextprotocol.kotlin.sdk.TextResourceContents
import io.modelcontextprotocol.kotlin.sdk.Tool
import io.modelcontextprotocol.kotlin.sdk.server.Server
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import okio.ByteString.Companion.toByteString

/**
 * This is a complex comment to test string processing.
 * It includes multiple lines with various characters:
 * * Special chars: "quotes", 'single-quotes', \backslashes\
 * * Symbols: @#$%^&*()_+-={}\[\]|;:<>,.?/
 * * Newlines and     multiple    spaces
 *
 * It also has empty lines and indentation:
 *   - Indented item 1
 *   - Indented item 2
 */
class McpVibeServiceClientImpl(
  val client: GrpcVibeServiceClient,
  val mcpServer: Server,
) : McpVibeServiceClient {
  override fun VibeServiceSetup() {
    SetVibeHandler()
    GetVibeHandler()
    SetVibeDetailsHandler()
    SetVibeArrayHandler()
    SetVibeObjectsHandler()
  }

  /**
   * This is a block comment
   * with multiple lines
   * to test block handling
   * "Hello World"
   */
  override fun SetVibeHandler() {
    mcpServer.addTool(
      name = "SetVibe",
      description = "This is a block comment with multiple lines to test block handling \"Hello World\"",
      inputSchema = Tool.Input(JsonObject(mapOf("vibe" to JsonPrimitive("vibe"))), required = listOf("vibe")),
      handler = { request ->
        val response = client.SetVibe(Json.decodeFromString<SetVibeRequest>(request.arguments.toString()))
        CallToolResult(
            content =
              listOf(
                TextContent(response.previous_vibe.toString()),
    TextContent(response.vibe.toString())
              ),
        )
      },
    )
    mcpServer.addResource(
      uri = "proto://SetVibeRequest",
      name = "SetVibeRequest",
      description = "Protocol buffer message for SetVibeRequest",
      mimeType = "application/json"
    ) { request ->
      ReadResourceResult(
        contents =
          listOf(
            TextResourceContents(
              text = "This is the SetVibeRequest resource.",
              uri = request.uri,
              mimeType = "application/json",
            ),
        ),
      )
    }
    mcpServer.addResource(
      uri = "proto://SetVibeResponse",
      name = "SetVibeResponse",
      description = "Protocol buffer message for SetVibeResponse",
      mimeType = "application/json"
    ) { request ->
      ReadResourceResult(
        contents =
          listOf(
            TextResourceContents(
              text = "This is the SetVibeResponse resource.",
              uri = request.uri,
              mimeType = "application/json",
            ),
        ),
      )
    }
  }

  /**
   * Get Vibe
   * of the server
   */
  override fun GetVibeHandler() {
    mcpServer.addTool(
      name = "GetVibe",
      description = "Get Vibe of the server",
      inputSchema = Tool.Input(JsonObject(mapOf()), required = listOf()),
      handler = { request ->
        val response = client.GetVibe(Json.decodeFromString<GetVibeRequest>(request.arguments.toString()))
        CallToolResult(
            content =
              listOf(
                TextContent(response.vibe.toString())
              ),
        )
      },
    )
    mcpServer.addResource(
      uri = "proto://GetVibeRequest",
      name = "GetVibeRequest",
      description = "Protocol buffer message for GetVibeRequest",
      mimeType = "application/json"
    ) { request ->
      ReadResourceResult(
        contents =
          listOf(
            TextResourceContents(
              text = "This is the GetVibeRequest resource.",
              uri = request.uri,
              mimeType = "application/json",
            ),
        ),
      )
    }
    mcpServer.addResource(
      uri = "proto://GetVibeResponse",
      name = "GetVibeResponse",
      description = "Protocol buffer message for GetVibeResponse",
      mimeType = "application/json"
    ) { request ->
      ReadResourceResult(
        contents =
          listOf(
            TextResourceContents(
              text = "This is the GetVibeResponse resource.",
              uri = request.uri,
              mimeType = "application/json",
            ),
        ),
      )
    }
  }

  /**
   * Set vibe details
   */
  override fun SetVibeDetailsHandler() {
    mcpServer.addTool(
      name = "SetVibeDetails",
      description = "Set vibe details",
      inputSchema = Tool.Input(JsonObject(mapOf("vibe" to JsonPrimitive("vibe"), "vibe_scalar" to JsonObject(mapOf("vibe_double" to JsonPrimitive("vibe_double"), "vibe_float" to JsonPrimitive("vibe_float"), "vibe_int32" to JsonPrimitive("vibe_int32"), "vibe_int64" to JsonPrimitive("vibe_int64"), "vibe_uint32" to JsonPrimitive("vibe_uint32"), "vibe_uint64" to JsonPrimitive("vibe_uint64"), "vibe_sint32" to JsonPrimitive("vibe_sint32"), "vibe_sint64" to JsonPrimitive("vibe_sint64"), "vibe_fixed32" to JsonPrimitive("vibe_fixed32"), "vibe_fixed64" to JsonPrimitive("vibe_fixed64"), "vibe_sfixed32" to JsonPrimitive("vibe_sfixed32"), "vibe_sfixed64" to JsonPrimitive("vibe_sfixed64"), "vibe_bool" to JsonPrimitive("vibe_bool"), "vibe_enum" to JsonPrimitive("vibe_enum"))))), required = listOf("vibe", "vibe_scalar")),
      handler = { request ->
        val response = client.SetVibeDetails(Json.decodeFromString<SetVibeDetailsRequest>(request.arguments.toString()))
        CallToolResult(
            content =
              listOf(
                TextContent(response.previous_vibe.toString()),
    TextContent(response.vibe.toString())
              ),
        )
      },
    )
    mcpServer.addResource(
      uri = "proto://SetVibeDetailsRequest",
      name = "SetVibeDetailsRequest",
      description = "Protocol buffer message for SetVibeDetailsRequest",
      mimeType = "application/json"
    ) { request ->
      ReadResourceResult(
        contents =
          listOf(
            TextResourceContents(
              text = "This is the SetVibeDetailsRequest resource.",
              uri = request.uri,
              mimeType = "application/json",
            ),
        ),
      )
    }
    mcpServer.addResource(
      uri = "proto://SetVibeDetailsResponse",
      name = "SetVibeDetailsResponse",
      description = "Protocol buffer message for SetVibeDetailsResponse",
      mimeType = "application/json"
    ) { request ->
      ReadResourceResult(
        contents =
          listOf(
            TextResourceContents(
              text = "This is the SetVibeDetailsResponse resource.",
              uri = request.uri,
              mimeType = "application/json",
            ),
        ),
      )
    }
  }

  /**
   * Set the vibe arrays
   */
  override fun SetVibeArrayHandler() {
    mcpServer.addTool(
      name = "SetVibeArray",
      description = "Set the vibe arrays",
      inputSchema = Tool.Input(JsonObject(mapOf("vibe_array" to JsonObject(mapOf("vibe_doubles" to JsonPrimitive("vibe_doubles"), "vibe_floats" to JsonPrimitive("vibe_floats"), "vibe_int32s" to JsonPrimitive("vibe_int32s"), "vibe_int64s" to JsonPrimitive("vibe_int64s"), "vibe_uint32s" to JsonPrimitive("vibe_uint32s"), "vibe_uint64s" to JsonPrimitive("vibe_uint64s"), "vibe_sint32s" to JsonPrimitive("vibe_sint32s"), "vibe_sint64s" to JsonPrimitive("vibe_sint64s"), "vibe_fixed32s" to JsonPrimitive("vibe_fixed32s"), "vibe_fixed64s" to JsonPrimitive("vibe_fixed64s"), "vibe_sfixed32s" to JsonPrimitive("vibe_sfixed32s"), "vibe_sfixed64s" to JsonPrimitive("vibe_sfixed64s"), "vibe_bools" to JsonPrimitive("vibe_bools"))))), required = listOf("vibe_array")),
      handler = { request ->
        val response = client.SetVibeArray(Json.decodeFromString<SetVibeArrayRequest>(request.arguments.toString()))
        CallToolResult(
            content =
              listOf(
                TextContent("{ " + "\"vibe_doubles\":" + "\"" + response.vibe_array?.vibe_doubles.toString() + "\", " + "\"vibe_floats\":" + "\"" + response.vibe_array?.vibe_floats.toString() + "\", " + "\"vibe_int32s\":" + "\"" + response.vibe_array?.vibe_int32s.toString() + "\", " + "\"vibe_int64s\":" + "\"" + response.vibe_array?.vibe_int64s.toString() + "\", " + "\"vibe_uint32s\":" + "\"" + response.vibe_array?.vibe_uint32s.toString() + "\", " + "\"vibe_uint64s\":" + "\"" + response.vibe_array?.vibe_uint64s.toString() + "\", " + "\"vibe_sint32s\":" + "\"" + response.vibe_array?.vibe_sint32s.toString() + "\", " + "\"vibe_sint64s\":" + "\"" + response.vibe_array?.vibe_sint64s.toString() + "\", " + "\"vibe_fixed32s\":" + "\"" + response.vibe_array?.vibe_fixed32s.toString() + "\", " + "\"vibe_fixed64s\":" + "\"" + response.vibe_array?.vibe_fixed64s.toString() + "\", " + "\"vibe_sfixed32s\":" + "\"" + response.vibe_array?.vibe_sfixed32s.toString() + "\", " + "\"vibe_sfixed64s\":" + "\"" + response.vibe_array?.vibe_sfixed64s.toString() + "\", " + "\"vibe_bools\":" + "\"" + response.vibe_array?.vibe_bools.toString() + "\"" + " }")
              ),
        )
      },
    )
    mcpServer.addResource(
      uri = "proto://SetVibeArrayRequest",
      name = "SetVibeArrayRequest",
      description = "Protocol buffer message for SetVibeArrayRequest",
      mimeType = "application/json"
    ) { request ->
      ReadResourceResult(
        contents =
          listOf(
            TextResourceContents(
              text = "This is the SetVibeArrayRequest resource.",
              uri = request.uri,
              mimeType = "application/json",
            ),
        ),
      )
    }
    mcpServer.addResource(
      uri = "proto://SetVibeArrayResponse",
      name = "SetVibeArrayResponse",
      description = "Protocol buffer message for SetVibeArrayResponse",
      mimeType = "application/json"
    ) { request ->
      ReadResourceResult(
        contents =
          listOf(
            TextResourceContents(
              text = "This is the SetVibeArrayResponse resource.",
              uri = request.uri,
              mimeType = "application/json",
            ),
        ),
      )
    }
  }

  /**
   * Set multiple vibe objects
   */
  override fun SetVibeObjectsHandler() {
    mcpServer.addTool(
      name = "SetVibeObjects",
      description = "Set multiple vibe objects",
      inputSchema = Tool.Input(JsonObject(mapOf("vibe_object" to JsonArray(listOf()))), required = listOf("vibe_object")),
      handler = { request ->
        val response = client.SetVibeObjects(Json.decodeFromString<SetVibeObjectsRequest>(request.arguments.toString()))
        CallToolResult(
            content =
              listOf(
                TextContent(response.vibe_object.map { "\"vibe\":" + "\"" + it.vibe.toString() + "\"" }.joinToString(prefix = "{", postfix = "}"))
              ),
        )
      },
    )
    mcpServer.addResource(
      uri = "proto://SetVibeObjectsRequest",
      name = "SetVibeObjectsRequest",
      description = "Protocol buffer message for SetVibeObjectsRequest",
      mimeType = "application/json"
    ) { request ->
      ReadResourceResult(
        contents =
          listOf(
            TextResourceContents(
              text = "This is the SetVibeObjectsRequest resource.",
              uri = request.uri,
              mimeType = "application/json",
            ),
        ),
      )
    }
    mcpServer.addResource(
      uri = "proto://SetVibeObjectsResponse",
      name = "SetVibeObjectsResponse",
      description = "Protocol buffer message for SetVibeObjectsResponse",
      mimeType = "application/json"
    ) { request ->
      ReadResourceResult(
        contents =
          listOf(
            TextResourceContents(
              text = "This is the SetVibeObjectsResponse resource.",
              uri = request.uri,
              mimeType = "application/json",
            ),
        ),
      )
    }
  }
}
