// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeDetailsRequest in examples/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlinx.serialization.Serializable
import kotlin.Int
import kotlin.Long
import kotlin.String

/**
 * The detailed vibe of the server
 *
 * @param vibe The vibe of the string to be set
 * @param vibe_scalar The details of the vibe
 */
@Serializable
class SetVibeDetailsRequest(
    @field:WireField(
        tag = 1,
        adapter = "com.squareup.wire.ProtoAdapter#STRING",
        label = WireField.Label.OMIT_IDENTITY,
        schemaIndex = 0,
    )
    val vibe: String = "",
    @field:WireField(
        tag = 2,
        adapter = "examples.v1.VibeScalar#ADAPTER",
        label = WireField.Label.OMIT_IDENTITY,
        jsonName = "vibeScalar",
        schemaIndex = 1,
    )
    val vibe_scalar: VibeScalar? = null,
) {
    fun copy(
        vibe: String = this.vibe,
        vibe_scalar: VibeScalar? = this.vibe_scalar,
    ): SetVibeDetailsRequest = SetVibeDetailsRequest(vibe, vibe_scalar)

    companion object {
        @JvmField
        val ADAPTER: ProtoAdapter<SetVibeDetailsRequest> =
            object : ProtoAdapter<SetVibeDetailsRequest>(
                FieldEncoding.LENGTH_DELIMITED,
                SetVibeDetailsRequest::class,
                "type.googleapis.com/examples.v1.SetVibeDetailsRequest",
                PROTO_3,
                null,
                "examples/v1/example.proto",
            ) {
                override fun encodedSize(`value`: SetVibeDetailsRequest): Int {
                    var size = 0
                    if (value.vibe != "") {
                        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.vibe)
                    }
                    if (value.vibe_scalar != null) {
                        size += VibeScalar.ADAPTER.encodedSizeWithTag(2, value.vibe_scalar)
                    }
                    return size
                }

                override fun encode(
                    writer: ProtoWriter,
                    `value`: SetVibeDetailsRequest,
                ) {
                    if (value.vibe != "") {
                        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.vibe)
                    }
                    if (value.vibe_scalar != null) {
                        VibeScalar.ADAPTER.encodeWithTag(writer, 2, value.vibe_scalar)
                    }
                }

                override fun encode(
                    writer: ReverseProtoWriter,
                    `value`: SetVibeDetailsRequest,
                ) {
                    if (value.vibe_scalar != null) {
                        VibeScalar.ADAPTER.encodeWithTag(writer, 2, value.vibe_scalar)
                    }
                    if (value.vibe != "") {
                        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.vibe)
                    }
                }

                override fun decode(reader: ProtoReader): SetVibeDetailsRequest {
                    var vibe: String = ""
                    var vibe_scalar: VibeScalar? = null
                    val unknownFields =
                        reader.forEachTag { tag ->
                            when (tag) {
                                1 -> vibe = ProtoAdapter.STRING.decode(reader)
                                2 -> vibe_scalar = VibeScalar.ADAPTER.decode(reader)
                                else -> reader.readUnknownField(tag)
                            }
                        }
                    return SetVibeDetailsRequest(
                        vibe = vibe,
                        vibe_scalar = vibe_scalar,
                    )
                }

                override fun redact(`value`: SetVibeDetailsRequest): SetVibeDetailsRequest =
                    value.copy(
                        vibe_scalar = value.vibe_scalar?.let(VibeScalar.ADAPTER::redact),
                    )
            }

        private const val serialVersionUID: Long = 0L
    }
}
