// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeArrayResponse in example/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Int
import kotlin.Long
import kotlinx.serialization.Serializable
import okio.ByteString.Companion.toByteString

/**
 * The vibe array response
 *
 * @param vibe_array The details of the vibe array
 */
@Serializable
class SetVibeArrayResponse(
  @field:WireField(
    tag = 1,
    adapter = "examples.v1.VibeArray#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "vibeArray",
    schemaIndex = 0,
  )
  val vibe_array: VibeArray? = null,
) {
  fun copy(vibe_array: VibeArray? = this.vibe_array): SetVibeArrayResponse = SetVibeArrayResponse(vibe_array)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<SetVibeArrayResponse> =
        object : ProtoAdapter<SetVibeArrayResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      SetVibeArrayResponse::class, 
      "type.googleapis.com/examples.v1.SetVibeArrayResponse", 
      PROTO_3, 
      null, 
      "example/v1/example.proto"
    ) {
      override fun encodedSize(`value`: SetVibeArrayResponse): Int {
        var size = 0
        if (value.vibe_array != null) {
          size += VibeArray.ADAPTER.encodedSizeWithTag(1, value.vibe_array)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SetVibeArrayResponse) {
        if (value.vibe_array != null) {
          VibeArray.ADAPTER.encodeWithTag(writer, 1, value.vibe_array)
        }
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SetVibeArrayResponse) {
        if (value.vibe_array != null) {
          VibeArray.ADAPTER.encodeWithTag(writer, 1, value.vibe_array)
        }
      }

      override fun decode(reader: ProtoReader): SetVibeArrayResponse {
        var vibe_array: VibeArray? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> vibe_array = VibeArray.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SetVibeArrayResponse(
          vibe_array = vibe_array,

        )
      }

      override fun redact(`value`: SetVibeArrayResponse): SetVibeArrayResponse = value.copy(
        vibe_array = value.vibe_array?.let(VibeArray.ADAPTER::redact)
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
