// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeObjectsResponse in example/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.redactElements
import kotlin.Int
import kotlin.Long
import kotlin.collections.List
import kotlinx.serialization.Serializable
import okio.ByteString.Companion.toByteString

/**
 * The response to set multiple vibe objects on the server
 *
 * @param vibe_object The details of the vibe
 */
@Serializable
class SetVibeObjectsResponse(
  @field:WireField(
    tag = 1,
    adapter = "examples.v1.VibeObject#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "vibeObject",
    schemaIndex = 0,
  )
  val vibe_object: List<VibeObject> = emptyList(),
) {
  fun copy(vibe_object: List<VibeObject> = this.vibe_object): SetVibeObjectsResponse = SetVibeObjectsResponse(vibe_object)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<SetVibeObjectsResponse> =
        object : ProtoAdapter<SetVibeObjectsResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      SetVibeObjectsResponse::class, 
      "type.googleapis.com/examples.v1.SetVibeObjectsResponse", 
      PROTO_3, 
      null, 
      "example/v1/example.proto"
    ) {
      override fun encodedSize(`value`: SetVibeObjectsResponse): Int {
        var size = 0
        size += VibeObject.ADAPTER.asRepeated().encodedSizeWithTag(1, value.vibe_object)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SetVibeObjectsResponse) {
        VibeObject.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.vibe_object)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SetVibeObjectsResponse) {
        VibeObject.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.vibe_object)
      }

      override fun decode(reader: ProtoReader): SetVibeObjectsResponse {
        val vibe_object = mutableListOf<VibeObject>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> vibe_object.add(VibeObject.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return SetVibeObjectsResponse(
          vibe_object = vibe_object,

        )
      }

      override fun redact(`value`: SetVibeObjectsResponse): SetVibeObjectsResponse = value.copy(
        vibe_object = value.vibe_object.redactElements(VibeObject.ADAPTER)
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
