// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SetVibeResponse in example/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlinx.serialization.Serializable
import okio.ByteString.Companion.toByteString

/**
 * the new vibe of the server
 */
@Serializable
class SetVibeResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "previousVibe",
    schemaIndex = 0,
  )
  val previous_vibe: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  val vibe: String = "",
) {
  fun copy(previous_vibe: String = this.previous_vibe, vibe: String = this.vibe): SetVibeResponse = SetVibeResponse(previous_vibe, vibe)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<SetVibeResponse> = object : ProtoAdapter<SetVibeResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      SetVibeResponse::class, 
      "type.googleapis.com/examples.v1.SetVibeResponse", 
      PROTO_3, 
      null, 
      "example/v1/example.proto"
    ) {
      override fun encodedSize(`value`: SetVibeResponse): Int {
        var size = 0
        if (value.previous_vibe != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.previous_vibe)
        }
        if (value.vibe != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.vibe)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SetVibeResponse) {
        if (value.previous_vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.previous_vibe)
        }
        if (value.vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.vibe)
        }
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SetVibeResponse) {
        if (value.vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.vibe)
        }
        if (value.previous_vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.previous_vibe)
        }
      }

      override fun decode(reader: ProtoReader): SetVibeResponse {
        var previous_vibe: String = ""
        var vibe: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> previous_vibe = ProtoAdapter.STRING.decode(reader)
            2 -> vibe = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SetVibeResponse(
          previous_vibe = previous_vibe,
          vibe = vibe,

        )
      }

      override fun redact(`value`: SetVibeResponse): SetVibeResponse = value
    }

    private const val serialVersionUID: Long = 0L
  }
}
