// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.SomeVibeObject in examples/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlinx.serialization.Serializable
import kotlin.Int
import kotlin.Long
import kotlin.String

/**
 * The vibe object of the server
 *
 * @param vibe The vibe of the server
 */
@Serializable
class SomeVibeObject(
    @field:WireField(
        tag = 1,
        adapter = "com.squareup.wire.ProtoAdapter#STRING",
        label = WireField.Label.OMIT_IDENTITY,
        schemaIndex = 0,
    )
    val vibe: String = "",
) {
    fun copy(vibe: String = this.vibe): SomeVibeObject = SomeVibeObject(vibe)

    companion object {
        @JvmField
        val ADAPTER: ProtoAdapter<SomeVibeObject> =
            object : ProtoAdapter<SomeVibeObject>(
                FieldEncoding.LENGTH_DELIMITED,
                SomeVibeObject::class,
                "type.googleapis.com/examples.v1.SomeVibeObject",
                PROTO_3,
                null,
                "examples/v1/example.proto",
            ) {
                override fun encodedSize(`value`: SomeVibeObject): Int {
                    var size = 0
                    if (value.vibe != "") {
                        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.vibe)
                    }
                    return size
                }

                override fun encode(
                    writer: ProtoWriter,
                    `value`: SomeVibeObject,
                ) {
                    if (value.vibe != "") {
                        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.vibe)
                    }
                }

                override fun encode(
                    writer: ReverseProtoWriter,
                    `value`: SomeVibeObject,
                ) {
                    if (value.vibe != "") {
                        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.vibe)
                    }
                }

                override fun decode(reader: ProtoReader): SomeVibeObject {
                    var vibe: String = ""
                    val unknownFields =
                        reader.forEachTag { tag ->
                            when (tag) {
                                1 -> vibe = ProtoAdapter.STRING.decode(reader)
                                else -> reader.readUnknownField(tag)
                            }
                        }
                    return SomeVibeObject(
                        vibe = vibe,
                    )
                }

                override fun redact(`value`: SomeVibeObject): SomeVibeObject = value
            }

        private const val serialVersionUID: Long = 0L
    }
}
