// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.VibeObject in example/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlinx.serialization.Serializable
import okio.ByteString.Companion.toByteString

/**
 * The vibe object of the server
 *
 * @param vibe The vibe of the server
 */
@Serializable
class VibeObject(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  val vibe: String = "",
) {
  fun copy(vibe: String = this.vibe): VibeObject = VibeObject(vibe)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<VibeObject> = object : ProtoAdapter<VibeObject>(
      FieldEncoding.LENGTH_DELIMITED, 
      VibeObject::class, 
      "type.googleapis.com/examples.v1.VibeObject", 
      PROTO_3, 
      null, 
      "example/v1/example.proto"
    ) {
      override fun encodedSize(`value`: VibeObject): Int {
        var size = 0
        if (value.vibe != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.vibe)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: VibeObject) {
        if (value.vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.vibe)
        }
      }

      override fun encode(writer: ReverseProtoWriter, `value`: VibeObject) {
        if (value.vibe != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.vibe)
        }
      }

      override fun decode(reader: ProtoReader): VibeObject {
        var vibe: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> vibe = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return VibeObject(
          vibe = vibe,

        )
      }

      override fun redact(`value`: VibeObject): VibeObject = value
    }

    private const val serialVersionUID: Long = 0L
  }
}
