// Code generated by Wire protocol buffer compiler, do not edit.
// Source: examples.v1.VibeArray in example/v1/example.proto
package examples.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Boolean
import kotlin.Double
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.collections.List
import kotlinx.serialization.Serializable
import okio.ByteString.Companion.toByteString

/**
 * The vibe array message
 *
 * @param vibe_doubles The details of the vibe double array
 * @param vibe_floats the details of the vibe float array
 * @param vibe_int32s The details of the vibe int32 array
 * @param vibe_int64s The details of the vibe int64 array
 * @param vibe_uint32s The details of the vibe uint32 array
 * @param vibe_uint64s The details of the vibe uint64 array
 * @param vibe_sint32s The details of the vibe sint32 array
 * @param vibe_sint64s The details of the vibe sint64 array
 * @param vibe_fixed32s The details of the vibe fixed32 array
 * @param vibe_fixed64s The details of the vibe fixed64 array
 * @param vibe_sfixed32s The details of the vibe sfixed32 array
 * @param vibe_sfixed64s The details of the vibe sfixed64 array
 * @param vibe_bools The details of the vibe bool array
 */
@Serializable
class VibeArray(
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    label = WireField.Label.PACKED,
    jsonName = "vibeDoubles",
    schemaIndex = 0,
  )
  val vibe_doubles: List<Double> = emptyList(),
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.PACKED,
    jsonName = "vibeFloats",
    schemaIndex = 1,
  )
  val vibe_floats: List<Float> = emptyList(),
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.PACKED,
    jsonName = "vibeInt32s",
    schemaIndex = 2,
  )
  val vibe_int32s: List<Int> = emptyList(),
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.PACKED,
    jsonName = "vibeInt64s",
    schemaIndex = 3,
  )
  val vibe_int64s: List<Long> = emptyList(),
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.PACKED,
    jsonName = "vibeUint32s",
    schemaIndex = 4,
  )
  val vibe_uint32s: List<Int> = emptyList(),
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.PACKED,
    jsonName = "vibeUint64s",
    schemaIndex = 5,
  )
  val vibe_uint64s: List<Long> = emptyList(),
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#SINT32",
    label = WireField.Label.PACKED,
    jsonName = "vibeSint32s",
    schemaIndex = 6,
  )
  val vibe_sint32s: List<Int> = emptyList(),
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#SINT64",
    label = WireField.Label.PACKED,
    jsonName = "vibeSint64s",
    schemaIndex = 7,
  )
  val vibe_sint64s: List<Long> = emptyList(),
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.PACKED,
    jsonName = "vibeFixed32s",
    schemaIndex = 8,
  )
  val vibe_fixed32s: List<Int> = emptyList(),
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED64",
    label = WireField.Label.PACKED,
    jsonName = "vibeFixed64s",
    schemaIndex = 9,
  )
  val vibe_fixed64s: List<Long> = emptyList(),
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#SFIXED32",
    label = WireField.Label.PACKED,
    jsonName = "vibeSfixed32s",
    schemaIndex = 10,
  )
  val vibe_sfixed32s: List<Int> = emptyList(),
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#SFIXED64",
    label = WireField.Label.PACKED,
    jsonName = "vibeSfixed64s",
    schemaIndex = 11,
  )
  val vibe_sfixed64s: List<Long> = emptyList(),
  @field:WireField(
    tag = 14,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.REPEATED,
    jsonName = "vibeBools",
    schemaIndex = 12,
  )
  val vibe_bools: List<Boolean> = emptyList(),
) {
  fun copy(
    vibe_doubles: List<Double> = this.vibe_doubles,
    vibe_floats: List<Float> = this.vibe_floats,
    vibe_int32s: List<Int> = this.vibe_int32s,
    vibe_int64s: List<Long> = this.vibe_int64s,
    vibe_uint32s: List<Int> = this.vibe_uint32s,
    vibe_uint64s: List<Long> = this.vibe_uint64s,
    vibe_sint32s: List<Int> = this.vibe_sint32s,
    vibe_sint64s: List<Long> = this.vibe_sint64s,
    vibe_fixed32s: List<Int> = this.vibe_fixed32s,
    vibe_fixed64s: List<Long> = this.vibe_fixed64s,
    vibe_sfixed32s: List<Int> = this.vibe_sfixed32s,
    vibe_sfixed64s: List<Long> = this.vibe_sfixed64s,
    vibe_bools: List<Boolean> = this.vibe_bools,
  ): VibeArray = VibeArray(vibe_doubles, vibe_floats, vibe_int32s, vibe_int64s, vibe_uint32s, vibe_uint64s, vibe_sint32s, vibe_sint64s, vibe_fixed32s, vibe_fixed64s, vibe_sfixed32s, vibe_sfixed64s, vibe_bools)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<VibeArray> = object : ProtoAdapter<VibeArray>(
      FieldEncoding.LENGTH_DELIMITED, 
      VibeArray::class, 
      "type.googleapis.com/examples.v1.VibeArray", 
      PROTO_3, 
      null, 
      "example/v1/example.proto"
    ) {
      override fun encodedSize(`value`: VibeArray): Int {
        var size = 0
        size += ProtoAdapter.DOUBLE.asPacked().encodedSizeWithTag(2, value.vibe_doubles)
        size += ProtoAdapter.FLOAT.asPacked().encodedSizeWithTag(3, value.vibe_floats)
        size += ProtoAdapter.INT32.asPacked().encodedSizeWithTag(4, value.vibe_int32s)
        size += ProtoAdapter.INT64.asPacked().encodedSizeWithTag(5, value.vibe_int64s)
        size += ProtoAdapter.UINT32.asPacked().encodedSizeWithTag(6, value.vibe_uint32s)
        size += ProtoAdapter.UINT64.asPacked().encodedSizeWithTag(7, value.vibe_uint64s)
        size += ProtoAdapter.SINT32.asPacked().encodedSizeWithTag(8, value.vibe_sint32s)
        size += ProtoAdapter.SINT64.asPacked().encodedSizeWithTag(9, value.vibe_sint64s)
        size += ProtoAdapter.FIXED32.asPacked().encodedSizeWithTag(10, value.vibe_fixed32s)
        size += ProtoAdapter.FIXED64.asPacked().encodedSizeWithTag(11, value.vibe_fixed64s)
        size += ProtoAdapter.SFIXED32.asPacked().encodedSizeWithTag(12, value.vibe_sfixed32s)
        size += ProtoAdapter.SFIXED64.asPacked().encodedSizeWithTag(13, value.vibe_sfixed64s)
        size += ProtoAdapter.BOOL.asRepeated().encodedSizeWithTag(14, value.vibe_bools)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: VibeArray) {
        ProtoAdapter.DOUBLE.asPacked().encodeWithTag(writer, 2, value.vibe_doubles)
        ProtoAdapter.FLOAT.asPacked().encodeWithTag(writer, 3, value.vibe_floats)
        ProtoAdapter.INT32.asPacked().encodeWithTag(writer, 4, value.vibe_int32s)
        ProtoAdapter.INT64.asPacked().encodeWithTag(writer, 5, value.vibe_int64s)
        ProtoAdapter.UINT32.asPacked().encodeWithTag(writer, 6, value.vibe_uint32s)
        ProtoAdapter.UINT64.asPacked().encodeWithTag(writer, 7, value.vibe_uint64s)
        ProtoAdapter.SINT32.asPacked().encodeWithTag(writer, 8, value.vibe_sint32s)
        ProtoAdapter.SINT64.asPacked().encodeWithTag(writer, 9, value.vibe_sint64s)
        ProtoAdapter.FIXED32.asPacked().encodeWithTag(writer, 10, value.vibe_fixed32s)
        ProtoAdapter.FIXED64.asPacked().encodeWithTag(writer, 11, value.vibe_fixed64s)
        ProtoAdapter.SFIXED32.asPacked().encodeWithTag(writer, 12, value.vibe_sfixed32s)
        ProtoAdapter.SFIXED64.asPacked().encodeWithTag(writer, 13, value.vibe_sfixed64s)
        ProtoAdapter.BOOL.asRepeated().encodeWithTag(writer, 14, value.vibe_bools)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: VibeArray) {
        ProtoAdapter.BOOL.asRepeated().encodeWithTag(writer, 14, value.vibe_bools)
        ProtoAdapter.SFIXED64.asPacked().encodeWithTag(writer, 13, value.vibe_sfixed64s)
        ProtoAdapter.SFIXED32.asPacked().encodeWithTag(writer, 12, value.vibe_sfixed32s)
        ProtoAdapter.FIXED64.asPacked().encodeWithTag(writer, 11, value.vibe_fixed64s)
        ProtoAdapter.FIXED32.asPacked().encodeWithTag(writer, 10, value.vibe_fixed32s)
        ProtoAdapter.SINT64.asPacked().encodeWithTag(writer, 9, value.vibe_sint64s)
        ProtoAdapter.SINT32.asPacked().encodeWithTag(writer, 8, value.vibe_sint32s)
        ProtoAdapter.UINT64.asPacked().encodeWithTag(writer, 7, value.vibe_uint64s)
        ProtoAdapter.UINT32.asPacked().encodeWithTag(writer, 6, value.vibe_uint32s)
        ProtoAdapter.INT64.asPacked().encodeWithTag(writer, 5, value.vibe_int64s)
        ProtoAdapter.INT32.asPacked().encodeWithTag(writer, 4, value.vibe_int32s)
        ProtoAdapter.FLOAT.asPacked().encodeWithTag(writer, 3, value.vibe_floats)
        ProtoAdapter.DOUBLE.asPacked().encodeWithTag(writer, 2, value.vibe_doubles)
      }

      override fun decode(reader: ProtoReader): VibeArray {
        var vibe_doubles: MutableList<Double>? = null
        var vibe_floats: MutableList<Float>? = null
        var vibe_int32s: MutableList<Int>? = null
        var vibe_int64s: MutableList<Long>? = null
        var vibe_uint32s: MutableList<Int>? = null
        var vibe_uint64s: MutableList<Long>? = null
        var vibe_sint32s: MutableList<Int>? = null
        var vibe_sint64s: MutableList<Long>? = null
        var vibe_fixed32s: MutableList<Int>? = null
        var vibe_fixed64s: MutableList<Long>? = null
        var vibe_sfixed32s: MutableList<Int>? = null
        var vibe_sfixed64s: MutableList<Long>? = null
        val vibe_bools = mutableListOf<Boolean>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            2 -> {
              if (vibe_doubles == null) {
                val minimumByteSize = 8
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_doubles = ArrayList(initialCapacity)
              }
              vibe_doubles!!.add(ProtoAdapter.DOUBLE.decode(reader))
            }
            3 -> {
              if (vibe_floats == null) {
                val minimumByteSize = 4
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_floats = ArrayList(initialCapacity)
              }
              vibe_floats!!.add(ProtoAdapter.FLOAT.decode(reader))
            }
            4 -> {
              if (vibe_int32s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_int32s = ArrayList(initialCapacity)
              }
              vibe_int32s!!.add(ProtoAdapter.INT32.decode(reader))
            }
            5 -> {
              if (vibe_int64s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_int64s = ArrayList(initialCapacity)
              }
              vibe_int64s!!.add(ProtoAdapter.INT64.decode(reader))
            }
            6 -> {
              if (vibe_uint32s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_uint32s = ArrayList(initialCapacity)
              }
              vibe_uint32s!!.add(ProtoAdapter.UINT32.decode(reader))
            }
            7 -> {
              if (vibe_uint64s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_uint64s = ArrayList(initialCapacity)
              }
              vibe_uint64s!!.add(ProtoAdapter.UINT64.decode(reader))
            }
            8 -> {
              if (vibe_sint32s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_sint32s = ArrayList(initialCapacity)
              }
              vibe_sint32s!!.add(ProtoAdapter.SINT32.decode(reader))
            }
            9 -> {
              if (vibe_sint64s == null) {
                val minimumByteSize = 1
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_sint64s = ArrayList(initialCapacity)
              }
              vibe_sint64s!!.add(ProtoAdapter.SINT64.decode(reader))
            }
            10 -> {
              if (vibe_fixed32s == null) {
                val minimumByteSize = 4
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_fixed32s = ArrayList(initialCapacity)
              }
              vibe_fixed32s!!.add(ProtoAdapter.FIXED32.decode(reader))
            }
            11 -> {
              if (vibe_fixed64s == null) {
                val minimumByteSize = 8
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_fixed64s = ArrayList(initialCapacity)
              }
              vibe_fixed64s!!.add(ProtoAdapter.FIXED64.decode(reader))
            }
            12 -> {
              if (vibe_sfixed32s == null) {
                val minimumByteSize = 4
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_sfixed32s = ArrayList(initialCapacity)
              }
              vibe_sfixed32s!!.add(ProtoAdapter.SFIXED32.decode(reader))
            }
            13 -> {
              if (vibe_sfixed64s == null) {
                val minimumByteSize = 8
                val initialCapacity = (reader.nextFieldMinLengthInBytes() / minimumByteSize)
                  .coerceAtMost(Int.MAX_VALUE.toLong())
                  .toInt()
                vibe_sfixed64s = ArrayList(initialCapacity)
              }
              vibe_sfixed64s!!.add(ProtoAdapter.SFIXED64.decode(reader))
            }
            14 -> vibe_bools.add(ProtoAdapter.BOOL.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return VibeArray(
          vibe_doubles = vibe_doubles ?: listOf(),
          vibe_floats = vibe_floats ?: listOf(),
          vibe_int32s = vibe_int32s ?: listOf(),
          vibe_int64s = vibe_int64s ?: listOf(),
          vibe_uint32s = vibe_uint32s ?: listOf(),
          vibe_uint64s = vibe_uint64s ?: listOf(),
          vibe_sint32s = vibe_sint32s ?: listOf(),
          vibe_sint64s = vibe_sint64s ?: listOf(),
          vibe_fixed32s = vibe_fixed32s ?: listOf(),
          vibe_fixed64s = vibe_fixed64s ?: listOf(),
          vibe_sfixed32s = vibe_sfixed32s ?: listOf(),
          vibe_sfixed64s = vibe_sfixed64s ?: listOf(),
          vibe_bools = vibe_bools,

        )
      }

      override fun redact(`value`: VibeArray): VibeArray = value
    }

    private const val serialVersionUID: Long = 0L
  }
}
